# Generated by Django 3.1.7 on 2021-04-20 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20210419_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
        migrations.AddField(
            model_name='photot',
            name='dateT',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='videot',
            name='dateT',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
