# Generated by Django 3.1.7 on 2021-05-18 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0003_auto_20210420_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobNumber', models.IntegerField()),
                ('apiId', models.CharField(max_length=10)),
                ('apiHash', models.CharField(max_length=40)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Message',
            new_name='MessageT',
        ),
        migrations.AddField(
            model_name='usert',
            name='firstName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usert',
            name='lastName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usert',
            name='userType',
            field=models.IntegerField(choices=[(0, 'User'), (1, 'atChat'), (2, 'Bot')], default=0),
        ),
        migrations.AlterField(
            model_name='groupt',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='groupt',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='photot',
            name='format',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='usert',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usert',
            name='idT',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usert',
            name='userName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='videot',
            name='format',
            field=models.CharField(max_length=5),
        ),
        migrations.DeleteModel(
            name='Number',
        ),
    ]
