# Generated by Django 3.1.7 on 2021-05-27 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_auto_20210527_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='numbert',
            name='session_key',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='numbert',
            name='apiId',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message='Not a number or a short one', regex='^(\\d{7})$')]),
        ),
        migrations.AlterField(
            model_name='numbert',
            name='mobNumber',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message='Not a number or a short one', regex='^(\\d{9,14})$')]),
        ),
    ]
