# Generated by Django 3.1.7 on 2021-06-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_auto_20210621_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupt',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
