# Generated by Django 3.1.7 on 2021-06-29 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_groupt_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbert',
            name='mobNumber',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.RegexValidator(message='Not a number or a short one', regex='^(\\d{9,14})$')]),
        ),
    ]
